version: '3'
services:
  sonar-mysql:
    image: mysql:5.7.23
    volumes:
      - ./mysql/create_sonar_database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
  tws-sonar:
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=password
      - SONARQUBE_JDBC_URL=jdbc:mysql://sonar-mysql:3306/sonar?useUnicode=true&characterEncoding=utf8